theme: minima
title: David Finol
tagline: Striving to create software that delights
description: David Finol's Personal Website
author: davidmfinol
social:
  links:
    - https://twitter.com/davidmfinol
    - https://github.com/davidmfinol
    - https://www.facebook.com/davidmfinol
    - https://www.linkedin.com/in/davidmfinol
minima:
  social_links:
    twitter: davidmfinol
    github: davidmfinol
    facebook: davidmfinol
    linkedin: davidmfinol
header_pages:
  - games.md
url: 'https://davidmfinol.com'
